// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr2CEG3t-rkK6eTU2v46UFW5ajfRqdIEU',
    appId: '1:433341645612:web:d6142f264deb86be7da289',
    messagingSenderId: '433341645612',
    projectId: 'hamro-note-3af45',
    authDomain: 'hamro-note-3af45.firebaseapp.com',
    storageBucket: 'hamro-note-3af45.appspot.com',
    measurementId: 'G-XSTJ9QQ0EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk4iFHgSAy65aIojKTG4k8v4M3G7p5qr4',
    appId: '1:433341645612:android:5fd841cafa528b7b7da289',
    messagingSenderId: '433341645612',
    projectId: 'hamro-note-3af45',
    storageBucket: 'hamro-note-3af45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1WX_Lh9EO-BTu3_0kCmPtMnw4DpZ2LP8',
    appId: '1:433341645612:ios:b456150bc070bf2d7da289',
    messagingSenderId: '433341645612',
    projectId: 'hamro-note-3af45',
    storageBucket: 'hamro-note-3af45.appspot.com',
    iosBundleId: 'com.example.hamroNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1WX_Lh9EO-BTu3_0kCmPtMnw4DpZ2LP8',
    appId: '1:433341645612:ios:3a4f7c11ab9c7a487da289',
    messagingSenderId: '433341645612',
    projectId: 'hamro-note-3af45',
    storageBucket: 'hamro-note-3af45.appspot.com',
    iosBundleId: 'com.example.hamroNoteApp.RunnerTests',
  );
}
